package com.model;
// Generated 10.10.2018 22:56:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private String nachname;
     private String vorname;
     private String adresse;
     private String email;
     private String passwort;
     private Set buches = new HashSet(0);

    public Person() {
    }

	
    public Person(String nachname, String vorname) {
        this.nachname = nachname;
        this.vorname = vorname;
    }
    public Person(String nachname, String vorname, String adresse, String email, String passwort, Set buches) {
       this.nachname = nachname;
       this.vorname = vorname;
       this.adresse = adresse;
       this.email = email;
       this.passwort = passwort;
       this.buches = buches;
    }
   
    public String getNachname() {
        return this.nachname;
    }
    
    public void setNachname(String nachname) {
        this.nachname = nachname;
    }
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPasswort() {
        return this.passwort;
    }
    
    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }
    public Set getBuches() {
        return this.buches;
    }
    
    public void setBuches(Set buches) {
        this.buches = buches;
        
    }




}


